### ISSUE TITLE
Asserting StubbedInstance

### ISSUE THREAD

**Issue by gavinvangent** [ttarnowski/ts-sinon#26]
Hi, I'm having problems with asserting, not sure if its a bug, or if I'm doing it wrong.

I have the following class:

```ts
// my-class.ts
import { Kinesis } from 'aws-sdk';

export class MyClass {
  constructor(public readonly name: string, public readonly kinesis: Kinesis) { }
  ...
}
```

I then want to run my assertions:

```ts
// my-class.test.ts
import { Kinesis } from 'aws-sdk';
import { StubbedInstance, stubInterface } from 'ts-sinon';
import { MyClass } from './my-class';

describe('MyClass', () => {
    const name = 'test-name';

    let kinesis: StubbedInstance<Kinesis>;
    let myClass: MyClass;

    beforeEach(() => {
        kinesis = stubInterface<Kinesis>();
        myClass = new MyClass(name, kinesis);
    });

    describe('constructor', () => {
        it('should construct an instance as expected', () => {
            myClass.should.be.deep.equal({
                name,
                kinesis
            });

            myClass.name.should.be.equal(name);
            myClass.kinesis.should.be.equal(kinesis);
        });
    });
});

```

which results in:
```sh
  1) MyClass
       constructor
         should construct an instance as expected:

      AssertionError: expected {} to equal undefined
      + expected - actual

      -{}
      +{
      +  "constructor": [Function]
      +  "inspect": {
      +    "callThrough": [Function]
      +    "callThroughWithNew": [Function]
      +    "callsArg": [Function]
      +    "callsArgAsync": [Function]
      +    "callsArgOn": [Function]
      +    "callsArgOnAsync": [Function]
      +    "callsArgOnWith": [Function]
      +    "callsArgOnWithAsync": [Function]
      +    "callsArgWith": [Function]
      +    "callsArgWithAsync": [Function]
      +    "callsFake": [Function]
      +    "create": [Function]
      +    "createStubInstance": [Function]
      +    "get": [Function]
      +    "onCall": [Function]
      +    "onFirstCall": [Function]
      +    "onSecondCall": [Function]
      +    "onThirdCall": [Function]
      +    "rejects": [Function]
      +    "reset": [Function]
      +    "resetBehavior": [Function]
      +    "resolves": [Function]
      +    "resolvesArg": [Function]
      +    "resolvesThis": [Function]
      +    "returns": [Function]
      +    "returnsArg": [Function]
      +    "returnsThis": [Function]
      +    "set": [Function]
      +    "throws": [Function]
      +    "throwsArg": [Function]
      +    "throwsException": [Function]
      +    "usingPromise": [Function]
      +    "value": [Function]
      +    "yields": [Function]
      +    "yieldsAsync": [Function]
      +    "yieldsOn": [Function]
      +    "yieldsOnAsync": [Function]
      +    "yieldsRight": [Function]
      +    "yieldsRightAsync": [Function]
      +    "yieldsTo": [Function]
      +    "yieldsToAsync": [Function]
      +    "yieldsToOn": [Function]
      +    "yieldsToOnAsync": [Function]
      +  }
      +  "should": {
      +    "__flags": {
      +      "lockSsfi": true
      +      "message": [null]
      +      "object": {}
      +      "ssfi": [Function]
      +    }
      +  }
      +}

      at Context.it (test/unit/my-class.test.ts:24:39)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I'd expect line 24 (`myClass.kinesis.should.be.equal(kinesis);`) to pass as I believe I'm asserting the reference to the same object. Any help is appreciated.

**Comment by gavinvangent** [comment]
I suspect this is related to https://github.com/ttarnowski/ts-sinon/issues/20 .

The surprising thing also to note is it compares the kinesis object without problems when used like this:
```ts
myClass.should.be.deep.equal({
  name,
  kinesis
});
```

but fails on line 24:
```ts
myClass.kinesis.should.be.equal(kinesis);
```

Since the first one is doing a `deepEquals`, I changed line 24 to:
```ts
myClass.kinesis.should.be.deep.equal(kinesis);
```
which still errors:

```sh
1) MyClass
       constructor
         should construct an instance as expected:

      AssertionError: expected {} to deeply equal undefined
      + expected - actual

      -{}
      +{
      +  "constructor": [Function]
      +  "inspect": {
      +    "callThrough": [Function]
      +    "callThroughWithNew": [Function]
      +    "callsArg": [Function]
      +    "callsArgAsync": [Function]
      +    "callsArgOn": [Function]
      +    "callsArgOnAsync": [Function]
      +    "callsArgOnWith": [Function]
      +    "callsArgOnWithAsync": [Function]
      +    "callsArgWith": [Function]
      +    "callsArgWithAsync": [Function]
      +    "callsFake": [Function]
      +    "create": [Function]
      +    "createStubInstance": [Function]
      +    "get": [Function]
      +    "onCall": [Function]
      +    "onFirstCall": [Function]
      +    "onSecondCall": [Function]
      +    "onThirdCall": [Function]
      +    "rejects": [Function]
      +    "reset": [Function]
      +    "resetBehavior": [Function]
      +    "resolves": [Function]
      +    "resolvesArg": [Function]
      +    "resolvesThis": [Function]
      +    "returns": [Function]
      +    "returnsArg": [Function]
      +    "returnsThis": [Function]
      +    "set": [Function]
      +    "throws": [Function]
      +    "throwsArg": [Function]
      +    "throwsException": [Function]
      +    "usingPromise": [Function]
      +    "value": [Function]
      +    "yields": [Function]
      +    "yieldsAsync": [Function]
      +    "yieldsOn": [Function]
      +    "yieldsOnAsync": [Function]
      +    "yieldsRight": [Function]
      +    "yieldsRightAsync": [Function]
      +    "yieldsTo": [Function]
      +    "yieldsToAsync": [Function]
      +    "yieldsToOn": [Function]
      +    "yieldsToOnAsync": [Function]
      +  }
      +  "should": {
      +    "__flags": {
      +      "deep": true
      +      "lockSsfi": true
      +      "message": [null]
      +      "object": {}
      +      "ssfi": [Function]
      +    }
      +  }
      +}

      at Context.it (test/unit/my-class.test.ts:24:44)
```

**Comment by charliewxyz** [comment]
It works for me like so:

```typescript
// index.ts
import { Kinesis } from 'aws-sdk';
import * as chai from 'chai';
import * as sinonChai from 'sinon-chai';
import { StubbedInstance, stubInterface } from 'ts-sinon';

const expect = chai.expect;
chai.use(sinonChai);

class MyClass {
  constructor(public readonly name: string, public readonly kinesis: Kinesis) { }
}

const kinesis: StubbedInstance<Kinesis> = stubInterface<Kinesis>();
const myClass: MyClass = new MyClass('test', kinesis);

expect(myClass).to.be.deep.equal({ name: 'test', kinesis });

expect(myClass.name).to.be.equal('test');
expect(myClass.kinesis).to.be.equal(kinesis);

myClass.kinesis.waitFor('streamExists');

expect(myClass.kinesis.waitFor).to.have.been.calledWith('streamExists');

console.log('ok');
```

```bash
$ npx ts-node index.ts
ok
```
